### ISSUE TITLE
Slack integration is broken.

### ISSUE THREAD

**Issue by frandallfarmer** [frandallfarmer/neohabitat#413]
This is at least 2 things:

slack.neohabitat.org doesn't work because 'slackin' is broken.

the bots also are mad...
```
error: Response not OK:  invalid_auth
error: Disconnecting because invalid_auth is not recoverable
error:  message=invalid_auth, stack=Error: invalid_auth
    at handleHttpResponse (/neohabitat/habibots/node_modules/@slack/client/lib/clients/transports/call-transport.js:103:17)
    at handleTransportResponse (/neohabitat/habibots/node_modules/@slack/client/lib/clients/transports/call-transport.js:153:19)
    at apply (/neohabitat/habibots/node_modules/lodash/lodash.js:478:17)
    at wrapper (/neohabitat/habibots/node_modules/lodash/lodash.js:5337:16)
    at Request.handleRequestTranportRes (/neohabitat/habibots/node_modules/@slack/client/lib/clients/transports/request.js:21:5)
    at apply (/neohabitat/habibots/node_modules/lodash/lodash.js:478:17)
    at Request.wrapper [as _callback] (/neohabitat/habibots/node_modules/lodash/lodash.js:5337:16)
    at self.callback (/neohabitat/habibots/node_modules/@slack/client/node_modules/request/request.js:186:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/neohabitat/habibots/node_modules/@slack/client/node_modules/request/request.js:1060:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/neohabitat/habibots/node_modules/@slack/client/node_modules/request/request.js:980:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by StuBlad** [comment]
slackin is no longer updated, but an actively developed fork exists. I don't know if it could be a drop in replacement for slackin, but it's a good place to start.

https://github.com/emedvedev/slackin-extended

Sharing this here because I'm not able to test this out myself, but if anyone is able to take a look at this, we could get Slack integration working again so we can see when people log into NeoHabitat.

**Comment by StuBlad** [comment]
We no longer need Slack integration, but it shouldn't be difficult to switch things over to use a Discord integration in conjunction with webhooks.

It would be nice to have newly hatched avatars appear in The MADE's Discord #newavatars channel which is where the Slack avatar logins would've been originally announced. A new "#login" or some equivalent channel could be made that announces the login of returning avatars to NeoHabitat as well so people can see who might be inworld at any given time.

It had a lot of utility when this feature worked before. If I saw someone had logged in, I'd often pop in and say hi and chat if I had time. Someone could setup a notification event on one of these channels as well if they wanted to be notified whenever someone logs in if they wanted to try and be around as much as possible.

**Comment by frandallfarmer** [comment]
Closing as superseded. The Slack integration is not coming back:

- The `@slack/client` v3 dependency was deliberately removed from habibots for unfixable CVEs in its `request`/`hawk`/`hoek` chain (`1074f425`); the RTM code paths in hatchery/greeter/connector are inert without it.
- slackin (slack.neohabitat.org) is dead upstream.
- The community moved to Discord, and as of 2026-07-01 the external-chat integration lives there via bridge_v2's webhook framework: a **logins** channel (debounced presence alerts — who materialized, where, humans-in-world count) and an **oracle-requests** channel (ASK/WISH speech to the Fountain/Crystal Ball/Genie/Bureaucrat, including `COMPLAINT:` moderator requests). Both validated live on prod.

Design + how to add more channels: `bridge_v2/DISCORD_ALERTS.md`. Remaining Slack-era code in habibots can be deleted at leisure; it runs nowhere.
